name: Build Agrichain

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Build images
              run: |
                docker compose up --build -d
                sleep 30
            
            - name: linting and formatting
              run: |
                docker exec agrichain_frontend bash -c "npm run lint;  npx prettier --check ."